/* Generated By:JavaCC: Do not edit this line. MyLanguageParserTreeConstants.java Version 4.1d1 */
public interface MyLanguageParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTALGORITHMNAME = 1;
  public int JJTVARIABLEFUNCTIONDECLARATIONS = 2;
  public int JJTDECLARATIONBLOCK = 3;
  public int JJTDECLARATION = 4;
  public int JJTTYPE = 5;
  public int JJTVARFUNCDECLARATIONTAIL = 6;
  public int JJTVARIABLEDECLARATION = 7;
  public int JJTVARIABLES = 8;
  public int JJTVARIABLETAIL = 9;
  public int JJTVARIABLE = 10;
  public int JJTVARIABLE2 = 11;
  public int JJTFUNCTIONDECLARATION = 12;
  public int JJTPARAMETERS = 13;
  public int JJTPARAMETERSTAIL = 14;
  public int JJTPARAMETER = 15;
  public int JJTMAINBLOCK = 16;
  public int JJTBLOCK = 17;
  public int JJTCONTENT = 18;
  public int JJTSTATEMENTS = 19;
  public int JJTSTATEMENTSTAIL = 20;
  public int JJTSTATEMENT = 21;
  public int JJTIFSTATEMENT = 22;
  public int JJTELSEIFSTATEMENT = 23;
  public int JJTELSESTATEMENT = 24;
  public int JJTCOMMENTSTATEMENT = 25;
  public int JJTRETURNSTATEMENT = 26;
  public int JJTBREAKSTATEMENT = 27;
  public int JJTPRINTSTATEMENT = 28;
  public int JJTPRINTARGUMENTS = 29;
  public int JJTPRINTARGUMENTSTAIL = 30;
  public int JJTPRINTARGUMENT = 31;
  public int JJTASSIGNMENTSTATEMENT = 32;
  public int JJTASSIGNMENTSTATEMENTTAIL = 33;
  public int JJTVARIABLEASSIGNMENT = 34;
  public int JJTFUNCTIONCALLASSIGNMENT = 35;
  public int JJTWHILESTATEMENT = 36;
  public int JJTBOOLEXPRESSION = 37;
  public int JJTBOOLEXPRESSIONTAIL = 38;
  public int JJTBTERM = 39;
  public int JJTBTERMTAIL = 40;
  public int JJTBFACTOR = 41;
  public int JJTBOOLVALUE = 42;
  public int JJTCOMPAREEXPRESSION = 43;
  public int JJTCOMPAREOPERATOR = 44;
  public int JJTARITHMETICEXPRESSION = 45;
  public int JJTARITHMETICEXPRESSIONTAIL = 46;
  public int JJTATERM = 47;
  public int JJTATERMTAIL = 48;
  public int JJTAFACTOR = 49;
  public int JJTFUNCTIONCALL = 50;


  public String[] jjtNodeName = {
    "Program",
    "AlgorithmName",
    "VariableFunctionDeclarations",
    "DeclarationBlock",
    "Declaration",
    "Type",
    "VarFuncDeclarationTail",
    "VariableDeclaration",
    "Variables",
    "VariableTail",
    "Variable",
    "Variable2",
    "FunctionDeclaration",
    "Parameters",
    "ParametersTail",
    "Parameter",
    "MainBlock",
    "Block",
    "Content",
    "Statements",
    "StatementsTail",
    "Statement",
    "IfStatement",
    "ElseIfStatement",
    "ElseStatement",
    "CommentStatement",
    "ReturnStatement",
    "BreakStatement",
    "PrintStatement",
    "PrintArguments",
    "PrintArgumentsTail",
    "PrintArgument",
    "AssignmentStatement",
    "AssignmentStatementTail",
    "VariableAssignment",
    "FunctionCallAssignment",
    "WhileStatement",
    "BoolExpression",
    "BoolExpressionTail",
    "BTerm",
    "BTermTail",
    "BFactor",
    "BoolValue",
    "CompareExpression",
    "CompareOperator",
    "ArithmeticExpression",
    "ArithmeticExpressionTail",
    "ATerm",
    "ATermTail",
    "AFactor",
    "FunctionCall",
  };
}
/* JavaCC - OriginalChecksum=51cc5733735ccc9e2a48bf863cf6624f (do not edit this line) */
